# Site settings
title: Shtinkhal Wagle
email: swagle@crimson.ua.edu
description: >-
  Mathematics student at The University of Alabama
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swagle7.github.io" # the base hostname & protocol for your site
repository: Swagle7/swagle7.github.io

# Author settings
author:
  name: Shrinkhal Wagle
  avatar: /assets/images/profile.jpg
  bio: BS Mathematics Student at The University of Alabama
  location: Tuscaloosa, AL
  email: swagle@crimson.ua.edu
  phone: 2058871017
  github: Swagle7
  #linkedin: NO LinkedIn # Updated LinkedIn username
  # Add other social media links as needed

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-last-modified-at

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  awards:
    output: true
    permalink: /:collection/:path/

# Display settings
data:
  display:
    homepage:
      show_news: false
      show_projects: false
      show_publications: false
      show_awards: false
      num_news: 5
      num_projects: 6
      num_publications: 5

# Scholar settings
scholar:
  style: apa
  locale: en
  sort_by: year,month
  order: descending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "bibliography"
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"

# Basic settings
lang: en
timezone: Asia/Kathmandu

# Analytics (Optional)
google_analytics: 

# Navigation
nav_order:
  - name: Home
    url: /
  - name: Projects
    url: /projects
  - name: Research
    url: /research
  - name: Resume
    url: /assets/resume.pdf

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore 